# Directory structure
SECONDARY_DATA_SOURCES = "data/Secondary_sources/"
PROCESSED_DATA_SOURCES = "data/Processed_data/"
CONCATENATED_DATA_SOURCES = "data/Concatenated_data/"

SATELLITE_DATA = "satellite_data/"
YEAR_2019 = "2019/"
YEAR_2020 = "2020/"

POP_DEN = "POP_DEN/"
LAND_USE = "LAND_USE/"
PRECIP = "PRECIP/"
NO2 = "NO2/"
AOD = "AOD/"
CITY = "CITY/"
CITY_ALL = "CITY_ALL/"
CITY_COLS = [
    "week",
    "country",
    "city",
    "count_co",
    "count_dew",
    "count_humidity",
    "count_no2",
    "count_o3",
    "count_pm10",
    "count_pm25",
    "count_precipitation",
    "count_pressure",
    "count_so2",
    "count_temperature",
    "count_uvi",
    "count_wd",
    "count_wind_gust",
    "count_wind_speed",
    "max_co",
    "max_dew",
    "max_humidity",
    "max_no2",
    "max_o3",
    "max_pm10",
    "max_pm25",
    "max_precipitation",
    "max_pressure",
    "max_so2",
    "max_temperature",
    "max_uvi",
    "max_wd",
    "max_wind_gust",
    "max_wind_speed",
    "median_co",
    "median_dew",
    "median_humidity",
    "median_no2",
    "median_o3",
    "median_pm10",
    "median_pm25",
    "median_precipitation",
    "median_pressure",
    "median_so2",
    "median_temperature",
    "median_uvi",
    "median_wd",
    "median_wind_gust",
    "median_wind_speed",
    "min_aqi",
    "min_co",
    "min_dew",
    "min_humidity",
    "min_no2",
    "min_o3",
    "min_pm10",
    "min_pm25",
    "min_precipitation",
    "min_pressure",
    "min_so2",
    "min_temperature",
    "min_uvi",
    "min_wd",
    "min_wind_gust",
    "min_wind_speed",
    "variance_aqi",
    "variance_co",
    "variance_dew",
    "variance_humidity",
    "variance_no2",
    "variance_o3",
    "variance_pm10",
    "variance_pm25",
    "variance_precipitation",
    "variance_pressure",
    "variance_so2",
    "variance_temperature",
    "variance_uvi",
    "variance_wd",
    "variance_wind_gust",
    "variance_wind_speed",
]
